- hosts: all
  become: true
  roles:
    - role: common
  # tasks:
  # - name: "SSH initialization"
  #   import_tasks: "./tasks/init-ssh.yml"

- hosts: masters
  roles:
    - role: master

- hosts: workers
  roles:
    - role: worker
