- name: "Ensure swap is disabled for current session"
  become: true
  ansible.builtin.command:
    cmd: "swapoff -a"
  when: ansible_facts['swaptotal_mb'] > 0
  changed_when: ansible_facts['swaptotal_mb'] > 0

- name: "Ensure swap is disabled permenentally in /etc/fstab"
  become: true
  ansible.posix.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
    backup: true
  loop:
    - none
    - swap
