- name: "Ensure swap is disabled for current session"
  command: "sudo swapoff -a"
  when: ansible_swaptotal_mb > 0
  changed_when: ansible_swaptotal_mb > 0

- name: "Ensure swap is disabled permenentally in /etc/fstab"
  become: true
  replace:
    path: "/etc/fstab"
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
    backup: true
